version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_asist
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_asist
      MYSQL_USER: asist_db
      MYSQL_PASSWORD: root
    volumes:
      - ../mysql:/var/lib/mysql
    ports:
      - "3312:3306"
    networks:
      - asist_network

  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile 
    container_name: nestjs_app
    restart: always
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: asist_db
      DATABASE_PASSWORD: root
      DATABASE_NAME: db_asist
      NODE_ENV: production
    ports:
      - "3001:3000"
    depends_on:
      - mysql
    networks:
      - asist_network

networks:
  asist_network:
    driver: bridge
